// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_VIBRATION_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_VIBRATION_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceVibrationListenerMethod0)(uint64_t, RustBuffer, int64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_VIBRATION_LISTENER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_VIBRATION_LISTENER_METHOD1
typedef void (*UniffiCallbackInterfaceVibrationListenerMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_VIBRATION_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_VIBRATION_LISTENER
typedef struct UniffiVTableCallbackInterfaceVibrationListener {
    UniffiCallbackInterfaceVibrationListenerMethod0 _Nonnull onVibration;
    UniffiCallbackInterfaceVibrationListenerMethod1 _Nonnull onEnd;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceVibrationListener;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CLONE_ENTRAINMENT
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CLONE_ENTRAINMENT
void*_Nonnull uniffi_resonator_ffi_fn_clone_entrainment(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_FREE_ENTRAINMENT
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_FREE_ENTRAINMENT
void uniffi_resonator_ffi_fn_free_entrainment(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_ENTRAINMENT_DAMP
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_ENTRAINMENT_DAMP
void uniffi_resonator_ffi_fn_method_entrainment_damp(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_ENTRAINMENT_POINT
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_ENTRAINMENT_POINT
RustBuffer uniffi_resonator_ffi_fn_method_entrainment_point(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CLONE_NODE
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CLONE_NODE
void*_Nonnull uniffi_resonator_ffi_fn_clone_node(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_FREE_NODE
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_FREE_NODE
void uniffi_resonator_ffi_fn_free_node(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CONSTRUCTOR_NODE_NEW
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CONSTRUCTOR_NODE_NEW
void*_Nonnull uniffi_resonator_ffi_fn_constructor_node_new(RustBuffer dir, int8_t offline, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_ADD_PEER
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_ADD_PEER
RustBuffer uniffi_resonator_ffi_fn_method_node_add_peer(void*_Nonnull ptr, RustBuffer name, RustBuffer ticket_or_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_CHAT_INIT
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_CHAT_INIT
void uniffi_resonator_ffi_fn_method_node_chat_init(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_CHAT_LOG
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_CHAT_LOG
RustBuffer uniffi_resonator_ffi_fn_method_node_chat_log(void*_Nonnull ptr, RustBuffer scope, int64_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_CHAT_SEND
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_CHAT_SEND
RustBuffer uniffi_resonator_ffi_fn_method_node_chat_send(void*_Nonnull ptr, RustBuffer target, RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_DB_PATH
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_DB_PATH
RustBuffer uniffi_resonator_ffi_fn_method_node_db_path(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_ENDPOINT_ID
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_ENDPOINT_ID
RustBuffer uniffi_resonator_ffi_fn_method_node_endpoint_id(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_ENTRAIN
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_ENTRAIN
void*_Nonnull uniffi_resonator_ffi_fn_method_node_entrain(void*_Nonnull ptr, RustBuffer point, void*_Nonnull listener, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_IS_SERVING
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_IS_SERVING
int8_t uniffi_resonator_ffi_fn_method_node_is_serving(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_LOCAL_EXECUTE
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_LOCAL_EXECUTE
RustBuffer uniffi_resonator_ffi_fn_method_node_local_execute(void*_Nonnull ptr, RustBuffer signal, RustBuffer params, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_LOCAL_QUERY
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_LOCAL_QUERY
RustBuffer uniffi_resonator_ffi_fn_method_node_local_query(void*_Nonnull ptr, RustBuffer signal, RustBuffer params, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_QUERY_PEER
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_QUERY_PEER
RustBuffer uniffi_resonator_ffi_fn_method_node_query_peer(void*_Nonnull ptr, RustBuffer peer, RustBuffer signal, RustBuffer modulation, RustBuffer params, RustBuffer timeout_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_SERVE
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_SERVE
RustBuffer uniffi_resonator_ffi_fn_method_node_serve(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_SPARQL
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_SPARQL
RustBuffer uniffi_resonator_ffi_fn_method_node_sparql(void*_Nonnull ptr, RustBuffer query, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_STOP
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_STOP
void uniffi_resonator_ffi_fn_method_node_stop(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_TICKET
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_TICKET
RustBuffer uniffi_resonator_ffi_fn_method_node_ticket(void*_Nonnull ptr, uint64_t wait_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_WAKE_OUTBOX
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_NODE_WAKE_OUTBOX
void uniffi_resonator_ffi_fn_method_node_wake_outbox(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CLONE_VIBRATIONLISTENER
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_CLONE_VIBRATIONLISTENER
void*_Nonnull uniffi_resonator_ffi_fn_clone_vibrationlistener(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_FREE_VIBRATIONLISTENER
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_FREE_VIBRATIONLISTENER
void uniffi_resonator_ffi_fn_free_vibrationlistener(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_INIT_CALLBACK_VTABLE_VIBRATIONLISTENER
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_INIT_CALLBACK_VTABLE_VIBRATIONLISTENER
void uniffi_resonator_ffi_fn_init_callback_vtable_vibrationlistener(UniffiVTableCallbackInterfaceVibrationListener* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_VIBRATIONLISTENER_ON_VIBRATION
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_VIBRATIONLISTENER_ON_VIBRATION
void uniffi_resonator_ffi_fn_method_vibrationlistener_on_vibration(void*_Nonnull ptr, RustBuffer point, int64_t seq, RustBuffer at, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_VIBRATIONLISTENER_ON_END
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_FN_METHOD_VIBRATIONLISTENER_ON_END
void uniffi_resonator_ffi_fn_method_vibrationlistener_on_end(void*_Nonnull ptr, RustBuffer reason, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_resonator_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_resonator_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_FREE
void ffi_resonator_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_resonator_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U8
void ffi_resonator_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U8
void ffi_resonator_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U8
void ffi_resonator_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_resonator_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I8
void ffi_resonator_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I8
void ffi_resonator_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I8
void ffi_resonator_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_resonator_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U16
void ffi_resonator_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U16
void ffi_resonator_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U16
void ffi_resonator_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_resonator_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I16
void ffi_resonator_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I16
void ffi_resonator_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I16
void ffi_resonator_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_resonator_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U32
void ffi_resonator_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U32
void ffi_resonator_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U32
void ffi_resonator_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_resonator_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I32
void ffi_resonator_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I32
void ffi_resonator_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I32
void ffi_resonator_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_resonator_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_U64
void ffi_resonator_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_U64
void ffi_resonator_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_U64
void ffi_resonator_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_resonator_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_I64
void ffi_resonator_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_I64
void ffi_resonator_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_I64
void ffi_resonator_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_resonator_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_F32
void ffi_resonator_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_F32
void ffi_resonator_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_F32
void ffi_resonator_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_resonator_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_F64
void ffi_resonator_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_F64
void ffi_resonator_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_F64
void ffi_resonator_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_resonator_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_POINTER
void ffi_resonator_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_resonator_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_POINTER
void ffi_resonator_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_resonator_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_resonator_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_resonator_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_resonator_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_resonator_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_POLL_VOID
void ffi_resonator_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_resonator_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_FREE_VOID
void ffi_resonator_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_resonator_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_ENTRAINMENT_DAMP
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_ENTRAINMENT_DAMP
uint16_t uniffi_resonator_ffi_checksum_method_entrainment_damp(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_ENTRAINMENT_POINT
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_ENTRAINMENT_POINT
uint16_t uniffi_resonator_ffi_checksum_method_entrainment_point(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_ADD_PEER
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_ADD_PEER
uint16_t uniffi_resonator_ffi_checksum_method_node_add_peer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_CHAT_INIT
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_CHAT_INIT
uint16_t uniffi_resonator_ffi_checksum_method_node_chat_init(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_CHAT_LOG
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_CHAT_LOG
uint16_t uniffi_resonator_ffi_checksum_method_node_chat_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_CHAT_SEND
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_CHAT_SEND
uint16_t uniffi_resonator_ffi_checksum_method_node_chat_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_DB_PATH
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_DB_PATH
uint16_t uniffi_resonator_ffi_checksum_method_node_db_path(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_ENDPOINT_ID
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_ENDPOINT_ID
uint16_t uniffi_resonator_ffi_checksum_method_node_endpoint_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_ENTRAIN
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_ENTRAIN
uint16_t uniffi_resonator_ffi_checksum_method_node_entrain(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_IS_SERVING
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_IS_SERVING
uint16_t uniffi_resonator_ffi_checksum_method_node_is_serving(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_LOCAL_EXECUTE
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_LOCAL_EXECUTE
uint16_t uniffi_resonator_ffi_checksum_method_node_local_execute(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_LOCAL_QUERY
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_LOCAL_QUERY
uint16_t uniffi_resonator_ffi_checksum_method_node_local_query(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_QUERY_PEER
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_QUERY_PEER
uint16_t uniffi_resonator_ffi_checksum_method_node_query_peer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_SERVE
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_SERVE
uint16_t uniffi_resonator_ffi_checksum_method_node_serve(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_SPARQL
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_SPARQL
uint16_t uniffi_resonator_ffi_checksum_method_node_sparql(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_STOP
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_STOP
uint16_t uniffi_resonator_ffi_checksum_method_node_stop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_TICKET
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_TICKET
uint16_t uniffi_resonator_ffi_checksum_method_node_ticket(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_WAKE_OUTBOX
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_NODE_WAKE_OUTBOX
uint16_t uniffi_resonator_ffi_checksum_method_node_wake_outbox(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_VIBRATIONLISTENER_ON_VIBRATION
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_VIBRATIONLISTENER_ON_VIBRATION
uint16_t uniffi_resonator_ffi_checksum_method_vibrationlistener_on_vibration(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_VIBRATIONLISTENER_ON_END
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_METHOD_VIBRATIONLISTENER_ON_END
uint16_t uniffi_resonator_ffi_checksum_method_vibrationlistener_on_end(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_CONSTRUCTOR_NODE_NEW
#define UNIFFI_FFIDEF_UNIFFI_RESONATOR_FFI_CHECKSUM_CONSTRUCTOR_NODE_NEW
uint16_t uniffi_resonator_ffi_checksum_constructor_node_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RESONATOR_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_RESONATOR_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_resonator_ffi_uniffi_contract_version(void
    
);
#endif

