// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(resonator_ffiFFI)
import resonator_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_resonator_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_resonator_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A live entrainment; dropping it does NOT damp (the session is held by
 * the runtime until `damp()` or node shutdown).
 */
public protocol EntrainmentProtocol : AnyObject {
    
    /**
     * Ends the entrainment in-band; `on_end` fires once the node
     * confirms. Idempotent.
     */
    func damp() 
    
    /**
     * The entrained point IRI.
     */
    func point()  -> String
    
}

/**
 * A live entrainment; dropping it does NOT damp (the session is held by
 * the runtime until `damp()` or node shutdown).
 */
open class Entrainment:
    EntrainmentProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_resonator_ffi_fn_clone_entrainment(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_resonator_ffi_fn_free_entrainment(pointer, $0) }
    }

    

    
    /**
     * Ends the entrainment in-band; `on_end` fires once the node
     * confirms. Idempotent.
     */
open func damp() {try! rustCall() {
    uniffi_resonator_ffi_fn_method_entrainment_damp(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * The entrained point IRI.
     */
open func point() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_resonator_ffi_fn_method_entrainment_point(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntrainment: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Entrainment

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Entrainment {
        return Entrainment(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Entrainment) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Entrainment {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Entrainment, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntrainment_lift(_ pointer: UnsafeMutableRawPointer) throws -> Entrainment {
    return try FfiConverterTypeEntrainment.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntrainment_lower(_ value: Entrainment) -> UnsafeMutableRawPointer {
    return FfiConverterTypeEntrainment.lower(value)
}




/**
 * A resonator node: one directory holding the sqlite database and the
 * ed25519 key. Constructing initializes the directory when needed.
 */
public protocol NodeProtocol : AnyObject {
    
    /**
     * Registers a peer under `name`. The target may be a dialing ticket
     * or a 64-hex endpoint id. Returns the peer's endpoint id.
     */
    func addPeer(name: String, ticketOrId: String) throws  -> String
    
    /**
     * Scaffolds chat on this node (tables, projection points, policy);
     * idempotent.
     */
    func chatInit() throws 
    
    /**
     * Reads chat history, newest first. `scope` filters to one
     * conversation (peer or room); `None` reads all.
     */
    func chatLog(scope: String?, limit: Int64) throws  -> [ChatMessage]
    
    /**
     * Sends a chat message to `target` (peer petname, 64-hex id, room
     * name, or room IRI). The send is an `_outbox` enqueue; delivery
     * happens while this node serves.
     */
    func chatSend(target: String, text: String) throws  -> SendReceipt
    
    /**
     * Path to the node's sqlite database (WAL; readable while serving).
     */
    func dbPath()  -> String
    
    /**
     * This node's 64-hex endpoint id.
     */
    func endpointId() throws  -> String
    
    /**
     * Entrains a Sympathetic `point` (its IRI, from `_projection`):
     * `listener.on_vibration` fires on every signal until `damp()` or
     * `on_end`. Owner lane: any registered Sympathetic point works, no
     * policy filter. Blocks until the node acknowledges.
     */
    func entrain(point: String, listener: VibrationListener) throws  -> Entrainment
    
    /**
     * Whether this node is currently serving.
     */
    func isServing()  -> Bool
    
    /**
     * [`local_query`] forced to a write (`rsntr:Execute`).
     */
    func localExecute(signal: String, params: [FfiValue]) throws  -> QueryResult
    
    /**
     * Runs `signal` on this node over the owner channel: no peer gate,
     * no authenticator chain, footprint-collected and audited, DDL
     * permitted. Classified Query/Execute from the text.
     */
    func localQuery(signal: String, params: [FfiValue]) throws  -> QueryResult
    
    /**
     * Sends `signal` to `peer` (petname or 64-hex id) under
     * `modulation` (usually "sql-sqlite" or "sparql"), classified
     * Query/Execute from the text.
     */
    func queryPeer(peer: String, signal: String, modulation: String, params: [FfiValue], timeoutMs: Int64?) throws  -> QueryResult
    
    /**
     * Starts serving on the crate's background runtime; returns the
     * direct socket addresses. Subsequent calls route to the serving
     * pipeline, so remote writes vibrate local entrainments.
     */
    func serve() throws  -> [String]
    
    /**
     * Runs a SPARQL text against this node's own store (owner channel).
     * SELECT/ASK answer rows; CONSTRUCT/DESCRIBE answer `turtle`;
     * updates answer `affected_rows`.
     */
    func sparql(query: String) throws  -> QueryResult
    
    /**
     * Stops serving (a no-op when not serving).
     */
    func stop() 
    
    /**
     * A shareable dialing ticket for the live serving endpoint, waiting
     * up to `wait_ms` for a direct address so the ticket is dialable
     * immediately. Requires `serve()` first.
     */
    func ticket(waitMs: UInt64) throws  -> String
    
    /**
     * Nudges the outbox worker to scan `_outbox` now. No-op when not
     * serving.
     */
    func wakeOutbox() 
    
}

/**
 * A resonator node: one directory holding the sqlite database and the
 * ed25519 key. Constructing initializes the directory when needed.
 */
open class Node:
    NodeProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_resonator_ffi_fn_clone_node(self.pointer, $0) }
    }
    /**
     * Opens (initializing on first use) the node directory. `offline`
     * binds serving to localhost with no relays (tests, LAN demos).
     */
public convenience init(dir: String, offline: Bool)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_constructor_node_new(
        FfiConverterString.lower(dir),
        FfiConverterBool.lower(offline),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_resonator_ffi_fn_free_node(pointer, $0) }
    }

    

    
    /**
     * Registers a peer under `name`. The target may be a dialing ticket
     * or a 64-hex endpoint id. Returns the peer's endpoint id.
     */
open func addPeer(name: String, ticketOrId: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_add_peer(self.uniffiClonePointer(),
        FfiConverterString.lower(name),
        FfiConverterString.lower(ticketOrId),$0
    )
})
}
    
    /**
     * Scaffolds chat on this node (tables, projection points, policy);
     * idempotent.
     */
open func chatInit()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_chat_init(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Reads chat history, newest first. `scope` filters to one
     * conversation (peer or room); `None` reads all.
     */
open func chatLog(scope: String?, limit: Int64)throws  -> [ChatMessage] {
    return try  FfiConverterSequenceTypeChatMessage.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_chat_log(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(scope),
        FfiConverterInt64.lower(limit),$0
    )
})
}
    
    /**
     * Sends a chat message to `target` (peer petname, 64-hex id, room
     * name, or room IRI). The send is an `_outbox` enqueue; delivery
     * happens while this node serves.
     */
open func chatSend(target: String, text: String)throws  -> SendReceipt {
    return try  FfiConverterTypeSendReceipt.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_chat_send(self.uniffiClonePointer(),
        FfiConverterString.lower(target),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Path to the node's sqlite database (WAL; readable while serving).
     */
open func dbPath() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_resonator_ffi_fn_method_node_db_path(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * This node's 64-hex endpoint id.
     */
open func endpointId()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_endpoint_id(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Entrains a Sympathetic `point` (its IRI, from `_projection`):
     * `listener.on_vibration` fires on every signal until `damp()` or
     * `on_end`. Owner lane: any registered Sympathetic point works, no
     * policy filter. Blocks until the node acknowledges.
     */
open func entrain(point: String, listener: VibrationListener)throws  -> Entrainment {
    return try  FfiConverterTypeEntrainment.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_entrain(self.uniffiClonePointer(),
        FfiConverterString.lower(point),
        FfiConverterTypeVibrationListener.lower(listener),$0
    )
})
}
    
    /**
     * Whether this node is currently serving.
     */
open func isServing() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_resonator_ffi_fn_method_node_is_serving(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * [`local_query`] forced to a write (`rsntr:Execute`).
     */
open func localExecute(signal: String, params: [FfiValue])throws  -> QueryResult {
    return try  FfiConverterTypeQueryResult.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_local_execute(self.uniffiClonePointer(),
        FfiConverterString.lower(signal),
        FfiConverterSequenceTypeFfiValue.lower(params),$0
    )
})
}
    
    /**
     * Runs `signal` on this node over the owner channel: no peer gate,
     * no authenticator chain, footprint-collected and audited, DDL
     * permitted. Classified Query/Execute from the text.
     */
open func localQuery(signal: String, params: [FfiValue])throws  -> QueryResult {
    return try  FfiConverterTypeQueryResult.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_local_query(self.uniffiClonePointer(),
        FfiConverterString.lower(signal),
        FfiConverterSequenceTypeFfiValue.lower(params),$0
    )
})
}
    
    /**
     * Sends `signal` to `peer` (petname or 64-hex id) under
     * `modulation` (usually "sql-sqlite" or "sparql"), classified
     * Query/Execute from the text.
     */
open func queryPeer(peer: String, signal: String, modulation: String, params: [FfiValue], timeoutMs: Int64?)throws  -> QueryResult {
    return try  FfiConverterTypeQueryResult.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_query_peer(self.uniffiClonePointer(),
        FfiConverterString.lower(peer),
        FfiConverterString.lower(signal),
        FfiConverterString.lower(modulation),
        FfiConverterSequenceTypeFfiValue.lower(params),
        FfiConverterOptionInt64.lower(timeoutMs),$0
    )
})
}
    
    /**
     * Starts serving on the crate's background runtime; returns the
     * direct socket addresses. Subsequent calls route to the serving
     * pipeline, so remote writes vibrate local entrainments.
     */
open func serve()throws  -> [String] {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_serve(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Runs a SPARQL text against this node's own store (owner channel).
     * SELECT/ASK answer rows; CONSTRUCT/DESCRIBE answer `turtle`;
     * updates answer `affected_rows`.
     */
open func sparql(query: String)throws  -> QueryResult {
    return try  FfiConverterTypeQueryResult.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_sparql(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Stops serving (a no-op when not serving).
     */
open func stop() {try! rustCall() {
    uniffi_resonator_ffi_fn_method_node_stop(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * A shareable dialing ticket for the live serving endpoint, waiting
     * up to `wait_ms` for a direct address so the ticket is dialable
     * immediately. Requires `serve()` first.
     */
open func ticket(waitMs: UInt64)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_resonator_ffi_fn_method_node_ticket(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(waitMs),$0
    )
})
}
    
    /**
     * Nudges the outbox worker to scan `_outbox` now. No-op when not
     * serving.
     */
open func wakeOutbox() {try! rustCall() {
    uniffi_resonator_ffi_fn_method_node_wake_outbox(self.uniffiClonePointer(),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNode: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Node

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Node {
        return Node(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Node) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Node {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Node, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNode_lift(_ pointer: UnsafeMutableRawPointer) throws -> Node {
    return try FfiConverterTypeNode.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNode_lower(_ value: Node) -> UnsafeMutableRawPointer {
    return FfiConverterTypeNode.lower(value)
}




/**
 * Foreign callback receiving one entrainment's signals.
 */
public protocol VibrationListener : AnyObject {
    
    /**
     * One vibration of the entrained point. `at` is the node's
     * `xsd:dateTime` timestamp when given.
     */
    func onVibration(point: String, seq: Int64, at: String?) 
    
    /**
     * The entrainment ended (damp confirmed, node shut down, or the
     * consumer was too slow); no further callbacks follow. `reason` is
     * `None` for a clean end.
     */
    func onEnd(reason: String?) 
    
}

/**
 * Foreign callback receiving one entrainment's signals.
 */
open class VibrationListenerImpl:
    VibrationListener {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_resonator_ffi_fn_clone_vibrationlistener(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_resonator_ffi_fn_free_vibrationlistener(pointer, $0) }
    }

    

    
    /**
     * One vibration of the entrained point. `at` is the node's
     * `xsd:dateTime` timestamp when given.
     */
open func onVibration(point: String, seq: Int64, at: String?) {try! rustCall() {
    uniffi_resonator_ffi_fn_method_vibrationlistener_on_vibration(self.uniffiClonePointer(),
        FfiConverterString.lower(point),
        FfiConverterInt64.lower(seq),
        FfiConverterOptionString.lower(at),$0
    )
}
}
    
    /**
     * The entrainment ended (damp confirmed, node shut down, or the
     * consumer was too slow); no further callbacks follow. `reason` is
     * `None` for a clean end.
     */
open func onEnd(reason: String?) {try! rustCall() {
    uniffi_resonator_ffi_fn_method_vibrationlistener_on_end(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(reason),$0
    )
}
}
    

}
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceVibrationListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceVibrationListener = UniffiVTableCallbackInterfaceVibrationListener(
        onVibration: { (
            uniffiHandle: UInt64,
            point: RustBuffer,
            seq: Int64,
            at: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeVibrationListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onVibration(
                     point: try FfiConverterString.lift(point),
                     seq: try FfiConverterInt64.lift(seq),
                     at: try FfiConverterOptionString.lift(at)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onEnd: { (
            uniffiHandle: UInt64,
            reason: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeVibrationListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEnd(
                     reason: try FfiConverterOptionString.lift(reason)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeVibrationListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface VibrationListener: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitVibrationListener() {
    uniffi_resonator_ffi_fn_init_callback_vtable_vibrationlistener(&UniffiCallbackInterfaceVibrationListener.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVibrationListener: FfiConverter {
    fileprivate static var handleMap = UniffiHandleMap<VibrationListener>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = VibrationListener

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> VibrationListener {
        return VibrationListenerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: VibrationListener) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VibrationListener {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: VibrationListener, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVibrationListener_lift(_ pointer: UnsafeMutableRawPointer) throws -> VibrationListener {
    return try FfiConverterTypeVibrationListener.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVibrationListener_lower(_ value: VibrationListener) -> UnsafeMutableRawPointer {
    return FfiConverterTypeVibrationListener.lower(value)
}


/**
 * One chat history entry (newest first from `chat_log`).
 */
public struct ChatMessage {
    public var id: String
    public var scope: String
    public var sender: String
    public var at: String
    public var receivedAt: String
    public var body: String
    public var blobHash: String?
    public var blobName: String?
    public var outgoing: Bool
    /**
     * `_outbox` delivery status of an outgoing message, when known.
     */
    public var status: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, scope: String, sender: String, at: String, receivedAt: String, body: String, blobHash: String?, blobName: String?, outgoing: Bool, 
        /**
         * `_outbox` delivery status of an outgoing message, when known.
         */status: String?) {
        self.id = id
        self.scope = scope
        self.sender = sender
        self.at = at
        self.receivedAt = receivedAt
        self.body = body
        self.blobHash = blobHash
        self.blobName = blobName
        self.outgoing = outgoing
        self.status = status
    }
}



extension ChatMessage: Equatable, Hashable {
    public static func ==(lhs: ChatMessage, rhs: ChatMessage) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.scope != rhs.scope {
            return false
        }
        if lhs.sender != rhs.sender {
            return false
        }
        if lhs.at != rhs.at {
            return false
        }
        if lhs.receivedAt != rhs.receivedAt {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        if lhs.blobHash != rhs.blobHash {
            return false
        }
        if lhs.blobName != rhs.blobName {
            return false
        }
        if lhs.outgoing != rhs.outgoing {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(scope)
        hasher.combine(sender)
        hasher.combine(at)
        hasher.combine(receivedAt)
        hasher.combine(body)
        hasher.combine(blobHash)
        hasher.combine(blobName)
        hasher.combine(outgoing)
        hasher.combine(status)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatMessage {
        return
            try ChatMessage(
                id: FfiConverterString.read(from: &buf), 
                scope: FfiConverterString.read(from: &buf), 
                sender: FfiConverterString.read(from: &buf), 
                at: FfiConverterString.read(from: &buf), 
                receivedAt: FfiConverterString.read(from: &buf), 
                body: FfiConverterString.read(from: &buf), 
                blobHash: FfiConverterOptionString.read(from: &buf), 
                blobName: FfiConverterOptionString.read(from: &buf), 
                outgoing: FfiConverterBool.read(from: &buf), 
                status: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ChatMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.scope, into: &buf)
        FfiConverterString.write(value.sender, into: &buf)
        FfiConverterString.write(value.at, into: &buf)
        FfiConverterString.write(value.receivedAt, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
        FfiConverterOptionString.write(value.blobHash, into: &buf)
        FfiConverterOptionString.write(value.blobName, into: &buf)
        FfiConverterBool.write(value.outgoing, into: &buf)
        FfiConverterOptionString.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lift(_ buf: RustBuffer) throws -> ChatMessage {
    return try FfiConverterTypeChatMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatMessage_lower(_ value: ChatMessage) -> RustBuffer {
    return FfiConverterTypeChatMessage.lower(value)
}


/**
 * One result row, values aligned to the result's `columns` (NULLs
 * materialized; the wire omits them).
 */
public struct FfiRow {
    public var values: [FfiValue]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(values: [FfiValue]) {
        self.values = values
    }
}



extension FfiRow: Equatable, Hashable {
    public static func ==(lhs: FfiRow, rhs: FfiRow) -> Bool {
        if lhs.values != rhs.values {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(values)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRow {
        return
            try FfiRow(
                values: FfiConverterSequenceTypeFfiValue.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRow, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiValue.write(value.values, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRow_lift(_ buf: RustBuffer) throws -> FfiRow {
    return try FfiConverterTypeFfiRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRow_lower(_ value: FfiRow) -> RustBuffer {
    return FfiConverterTypeFfiRow.lower(value)
}


/**
 * A successful query/execute: rows plus the `rsntr:Done` trailer facts.
 * A sparql CONSTRUCT/DESCRIBE answers with `turtle` set and no rows.
 */
public struct QueryResult {
    public var columns: [String]
    public var rows: [FfiRow]
    public var rowCount: Int64?
    public var affectedRows: Int64?
    public var lastInsertRowid: Int64?
    public var truncated: Bool
    public var turtle: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(columns: [String], rows: [FfiRow], rowCount: Int64?, affectedRows: Int64?, lastInsertRowid: Int64?, truncated: Bool, turtle: String?) {
        self.columns = columns
        self.rows = rows
        self.rowCount = rowCount
        self.affectedRows = affectedRows
        self.lastInsertRowid = lastInsertRowid
        self.truncated = truncated
        self.turtle = turtle
    }
}



extension QueryResult: Equatable, Hashable {
    public static func ==(lhs: QueryResult, rhs: QueryResult) -> Bool {
        if lhs.columns != rhs.columns {
            return false
        }
        if lhs.rows != rhs.rows {
            return false
        }
        if lhs.rowCount != rhs.rowCount {
            return false
        }
        if lhs.affectedRows != rhs.affectedRows {
            return false
        }
        if lhs.lastInsertRowid != rhs.lastInsertRowid {
            return false
        }
        if lhs.truncated != rhs.truncated {
            return false
        }
        if lhs.turtle != rhs.turtle {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(columns)
        hasher.combine(rows)
        hasher.combine(rowCount)
        hasher.combine(affectedRows)
        hasher.combine(lastInsertRowid)
        hasher.combine(truncated)
        hasher.combine(turtle)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQueryResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QueryResult {
        return
            try QueryResult(
                columns: FfiConverterSequenceString.read(from: &buf), 
                rows: FfiConverterSequenceTypeFfiRow.read(from: &buf), 
                rowCount: FfiConverterOptionInt64.read(from: &buf), 
                affectedRows: FfiConverterOptionInt64.read(from: &buf), 
                lastInsertRowid: FfiConverterOptionInt64.read(from: &buf), 
                truncated: FfiConverterBool.read(from: &buf), 
                turtle: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: QueryResult, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.columns, into: &buf)
        FfiConverterSequenceTypeFfiRow.write(value.rows, into: &buf)
        FfiConverterOptionInt64.write(value.rowCount, into: &buf)
        FfiConverterOptionInt64.write(value.affectedRows, into: &buf)
        FfiConverterOptionInt64.write(value.lastInsertRowid, into: &buf)
        FfiConverterBool.write(value.truncated, into: &buf)
        FfiConverterOptionString.write(value.turtle, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueryResult_lift(_ buf: RustBuffer) throws -> QueryResult {
    return try FfiConverterTypeQueryResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQueryResult_lower(_ value: QueryResult) -> RustBuffer {
    return FfiConverterTypeQueryResult.lower(value)
}


/**
 * The receipt of a `chat_send`: the send is an `_outbox` enqueue;
 * delivery happens while the node serves.
 */
public struct SendReceipt {
    public var messageId: String
    public var scope: String
    public var queuedTo: [String]
    public var blobHash: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(messageId: String, scope: String, queuedTo: [String], blobHash: String?) {
        self.messageId = messageId
        self.scope = scope
        self.queuedTo = queuedTo
        self.blobHash = blobHash
    }
}



extension SendReceipt: Equatable, Hashable {
    public static func ==(lhs: SendReceipt, rhs: SendReceipt) -> Bool {
        if lhs.messageId != rhs.messageId {
            return false
        }
        if lhs.scope != rhs.scope {
            return false
        }
        if lhs.queuedTo != rhs.queuedTo {
            return false
        }
        if lhs.blobHash != rhs.blobHash {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(messageId)
        hasher.combine(scope)
        hasher.combine(queuedTo)
        hasher.combine(blobHash)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendReceipt: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendReceipt {
        return
            try SendReceipt(
                messageId: FfiConverterString.read(from: &buf), 
                scope: FfiConverterString.read(from: &buf), 
                queuedTo: FfiConverterSequenceString.read(from: &buf), 
                blobHash: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SendReceipt, into buf: inout [UInt8]) {
        FfiConverterString.write(value.messageId, into: &buf)
        FfiConverterString.write(value.scope, into: &buf)
        FfiConverterSequenceString.write(value.queuedTo, into: &buf)
        FfiConverterOptionString.write(value.blobHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendReceipt_lift(_ buf: RustBuffer) throws -> SendReceipt {
    return try FfiConverterTypeSendReceipt.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendReceipt_lower(_ value: SendReceipt) -> RustBuffer {
    return FfiConverterTypeSendReceipt.lower(value)
}


public enum FfiError {

    
    
    /**
     * Connection, engine, protocol, or local failure.
     */
    case Failure(msg: String
    )
    /**
     * The serving side's authenticator or policy said no.
     */
    case Denied(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Failure(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Denied(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Failure(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Denied(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * One envelope value crossing the FFI. `BlobRef` results (blobs beyond
 * the frame cap) arrive as `Text` carrying the `blake3:<hex>` hash.
 */

public enum FfiValue {
    
    case null
    case integer(v: Int64
    )
    case real(v: Double
    )
    case text(v: String
    )
    case blob(v: Data
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiValue: FfiConverterRustBuffer {
    typealias SwiftType = FfiValue

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiValue {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .null
        
        case 2: return .integer(v: try FfiConverterInt64.read(from: &buf)
        )
        
        case 3: return .real(v: try FfiConverterDouble.read(from: &buf)
        )
        
        case 4: return .text(v: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .blob(v: try FfiConverterData.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiValue, into buf: inout [UInt8]) {
        switch value {
        
        
        case .null:
            writeInt(&buf, Int32(1))
        
        
        case let .integer(v):
            writeInt(&buf, Int32(2))
            FfiConverterInt64.write(v, into: &buf)
            
        
        case let .real(v):
            writeInt(&buf, Int32(3))
            FfiConverterDouble.write(v, into: &buf)
            
        
        case let .text(v):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v, into: &buf)
            
        
        case let .blob(v):
            writeInt(&buf, Int32(5))
            FfiConverterData.write(v, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValue_lift(_ buf: RustBuffer) throws -> FfiValue {
    return try FfiConverterTypeFfiValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValue_lower(_ value: FfiValue) -> RustBuffer {
    return FfiConverterTypeFfiValue.lower(value)
}



extension FfiValue: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeChatMessage: FfiConverterRustBuffer {
    typealias SwiftType = [ChatMessage]

    public static func write(_ value: [ChatMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChatMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChatMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChatMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChatMessage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiRow: FfiConverterRustBuffer {
    typealias SwiftType = [FfiRow]

    public static func write(_ value: [FfiRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiRow.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiValue: FfiConverterRustBuffer {
    typealias SwiftType = [FfiValue]

    public static func write(_ value: [FfiValue], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiValue.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiValue] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiValue]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiValue.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_resonator_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_entrainment_damp() != 36285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_entrainment_point() != 20330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_add_peer() != 25651) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_chat_init() != 21198) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_chat_log() != 40246) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_chat_send() != 29790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_db_path() != 22430) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_endpoint_id() != 1104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_entrain() != 42183) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_is_serving() != 6494) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_local_execute() != 30344) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_local_query() != 56599) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_query_peer() != 24285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_serve() != 16508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_sparql() != 11957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_stop() != 19991) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_ticket() != 17519) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_node_wake_outbox() != 7461) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_vibrationlistener_on_vibration() != 63114) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_method_vibrationlistener_on_end() != 58233) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resonator_ffi_checksum_constructor_node_new() != 30471) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitVibrationListener()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all